### ISSUE TITLE
Add support for building other modules from spec

### ISSUE THREAD

**Issue by jgrund** [intel-hpdd/module-tools#9]
The following code is gated on just PyPI modules, but really it could be used to build any spec that can pull it's source0.

https://github.com/intel-hpdd/module-tools/blob/0cf29e32e9c1e5635497c28e0eeab76f78855403/copr.mk#L22-L33

Look at removing the else case and always building from spec.

**Comment by brianjmurrell** [comment]
But notice the comment inside the PyPI gate.  The PyPI gate is actually supposed/wanting to be using ` copr-cli buildpypi --packagename $(NAME)` and is only temporarily using `copr-cli $(COPR_CONFIG) build $(OWNER_PROJECT) $^ ` until https://pagure.io/copr/copr/issue/207 is worked out.

So while I suspect that the more common case for the else clause is to use the same `copr-cli $(COPR_CONFIG) build $(OWNER_PROJECT) $^` and have another gate for any particular type of module that needs `copr-cli $(COPR_CONFIG) buildmock $(OWNER_PROJECT) ...`, un-gating the PyPI clause is not the right solution.

**Comment by jgrund** [comment]
I wonder if it's best to gate on registry type than specifying build-type directly. Not sure if each registry is one-size-fits-all.
